directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
    DuplicateMethodCall:
      enabled: false
    TooManyStatements:
      max_statements: 10
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
    DuplicateMethodCall:
      max_calls: 2
  "app/models":
    InstanceVariableAssumption:
      enabled: false
  "db/migrate":
    UncommunicativeVariableName:
      enabled: false
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    IrresponsibleModule:
      enabled: false
